nix-daemon: bump to 2.12 cluster-wide
2.11 suffers from an annoying remote builder bug related leading to corrupted NARs transfers,
symbolized by:

```
error: not an absolute path: 'nix-archive-1'
error: builder for '/nix/store/7lcnj093a6qs1d1ng4lpxsxw1hlla980-squashfs.img.drv' failed with exit code 1
```

They often happens when you copy large files over the wire, e.g. VM tests, etc.